window.classesData = {
    classes_list: [
        { id: 'barb_menu', title: 'Варвар' },
        { id: 'wizard_menu', title: 'Чародей' },
        { id: 'dh_menu', title: 'Охотник на демонов' },
        { id: 'monk_menu', title: 'Монах' },
        { id: 'wd_menu', title: 'Колдун' },
        { id: 'crusader_menu', title: 'Крестоносец' },
    ],
    // ВАРВАР
    barb_menu: [
        { id: 'barb_buffalo', title: 'Буйвол' },
        { id: 'barb_blade', title: 'Лезвие' },
        { id: 'barb_king', title: 'Бессмертный король' },
        { id: 'barb_golem', title: 'Голем' },
        { id: 'barb_tyrant', title: 'Тирант' }
    ],
    barb_buffalo: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/raekors-striders-Unique_Boots_Set_05_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+щит, 70🌒 2руч</p><p>🛡️ — <b>Наследие рекор</b></p><p>1, 2 Профа — Далгурский оазис, Диабло</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Нападение и защита | 2️⃣ Буйство<br>3️⃣ Суеверие | 4️⃣ ❗Стальные нервы❗, Остервенение<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Сокрушительный удар | 2️⃣ Молот древних<br>3️⃣ Любое | 4️⃣ Яростный рывок<br>5️⃣ Любое | 6️⃣ ❗Удар в прыжке❗, Любое` },
    barb_blade: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/cuirass-of-the-wastes-Unique_Chest_Set_01_p2'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 Любое</p><p>🛡️ — <b>Гнев пустошей</b></p><p>1, 2 Профа — серебряный шпиль 1, Белиал</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Остервенение | 2️⃣ Задира | 3️⃣ Кровожадность<br>4️⃣ ❗Стальные нервы❗, Твердость<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любое | 2️⃣ Рваные раны + Вихрь<br>3️⃣ ❗Удар в прыжке❗, Любое | 4️⃣ Сверхсила<br>5️⃣ Любое | 6️⃣ —` },
    barb_king: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/immortal-kings-eternal-reign-Unique_Chest_013_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 2руч, 70🌒 1+щит</p><p>🛡️ — <b>Бессмертный король</b></p><p>1, 2 Профа — гиблые поля, осадный зверь</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Милость Булкатоса | 2️⃣ Твердость | 3️⃣ Буйство<br>4️⃣ ❗Стальные нервы❗, Задира ИЛИ Ярость берсерка<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любое | 2️⃣ Любое | 3️⃣ ❗Удар в прыжке❗, Любое<br>4️⃣ — | 5️⃣ Любое | 6️⃣ Гнев берсерка + Зов древних` },
    barb_golem: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/spirit-of-the-earth-Unique_Chest_Set_15_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 2руч, 70🌒 1+щит</p><p>🛡️ — <b>Мощь земли</b></p><p>1, 2 Профа — Поле боя, Адрия</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Мощь земли | 2️⃣ Твердость | 3️⃣ Враждебность<br>4️⃣ ❗Стальные нервы❗, Остервенение<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Рассекающий удар | 2️⃣ Сейсмический удар ИЛИ Копьё<br>3️⃣ Удар в прыжке + Топот | 4️⃣ Лавина<br>5️⃣ — | 6️⃣ Землетрясение` },
    barb_tyrant: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/markings-of-savages-P68_Unique_Chest_Set_05'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+1</p><p>🛡️ — <b>Девяносто неистовых</b></p><p>1, 2 Профа — архивы золтуна кулла, Магда</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Ободряющий пример | 2️⃣ Ярость берсерка<br>3️⃣ Беспощадность | 4️⃣ ❗Стальные нервы❗, Суеверие<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Бешенство | 2️⃣ — | 3️⃣ ❗Удар в прыжке❗, Любое<br>4️⃣ Отмщение | 5️⃣ Угрожающий + Боевой + Воинственный крики<br>6️⃣ —` },

    // ОХОТНИК
    dh_menu: [
        { id: 'dh_death', title: 'Смерть демона' },
        { id: 'dh_shadow', title: 'Тень' },
        { id: 'dh_vengeance', title: 'Отмщение' },
        { id: 'dh_hawk', title: 'Ястреб' },
        { id: 'dh_marauder', title: 'Мародёр' }
    ],
    dh_death: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/natalyas-sight-Unique_Helm_009_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 2 арбалета, 70🌒 1 арб + колчан</p><p>🛡️ — <b>Наталия</b></p><p>1, 2 Профа — Далгурский оазис, Раканот</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Гренадер | 2️⃣ Твердая рука<br>3️⃣ Вершина мастерства | 4️⃣ ❗Бдительность❗, Самоисцеление<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Гранаты | 2️⃣ Скоростная стрельба | 3️⃣ Дымовая завеса<br>4️⃣ ❗Кульбит❗, На изготовку | 5️⃣ Шипастая ловушка | 6️⃣ Ливень возмездия` },
    dh_shadow: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/the-shadows-bane-Unique_Chest_Set_14_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1 + колчан, 70🌒 1 + щит</p><p>🛡️ — <b>Тень</b></p><p>1, 2 Профа — Руины корвуса, Штурмовой зверь</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Охота на одиночку | 2️⃣ Жаркая погоня<br>3️⃣ Засада | 4️⃣ ❗Бдительность❗, Сковывающие ловушки<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Болас | 2️⃣ Бросок кинжала | 3️⃣ Сила тьмы + Шипы<br>4️⃣ ❗Кульбит❗, Метка смерти | 5️⃣ Веер клинков | 6️⃣ —` },
    dh_vengeance: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/galvanized-vest-P69_Unique_Chest_Set_06'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 Лук + колчан, 70🌒 1арб + колчан ИЛИ щит</p><p>🛡️ — <b>Шестерни мертвых земель</b></p><p>1, 2 Профа — Руины корвуса, Диабло</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ ❗Бдительность❗, Ночной охотник | 2️⃣ Тактическое превосходство<br>3️⃣ Засада | 4️⃣ Самоисцеление<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любое | 2️⃣ Любое | 3️⃣ Шипы ИЛИ Сила тьмы<br>4️⃣ ❗Кульбит❗, Любое | 5️⃣ Возмездие | 6️⃣ Обстрел` },
    dh_hawk: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/cage-of-the-hellborn-Unique_Chest_Set_03_p2'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 Лук + колчан, 70🌒 2руч арб + колчан</p><p>🛡️ — <b>Сущность порока</b></p><p>1, 2 Профа — Нижние этажи 1, Диабло</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Самоисцеление | 2️⃣ Баллистика<br>3️⃣ Засада | 4️⃣ ❗Бдительность❗, Охотничий азарт<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Сам. стрела ИЛИ Замедл. выстрел | 2️⃣ Стрела стихий<br>3️⃣ Сила тьмы | 4️⃣ ❗Кульбит❗, На изготовку | 5️⃣ Возмездие | 6️⃣ Залп` },
    dh_marauder: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/marauders-carapace-Unique_Chest_Set_07_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 2руч арб + колчан, 70🌒 лук + колчан</p><p>🛡️ — <b>Мародер</b></p><p>1, 2 Профа — Архивы Золтуна Кулла, Магда</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Доработка механизмов | 2️⃣ Баллистика<br>3️⃣ Раздумья | 4️⃣ ❗Бдительность❗, Тактическое превосходство<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Отход под прикрытием | 2️⃣ Шакрам ИЛИ Стрела Стихий<br>3️⃣ ❗Кульбит❗, Сила Тьмы | 4️⃣ Питомец | 5️⃣ Турель | 6️⃣ Разрывная стрела ИЛИ Залп` },

    // ЧАРОДЕЙ
    wizard_menu: [
        { id: 'wiz_archon', title: 'Архонт' },
        { id: 'wiz_elements', title: '4 стихии' },
        { id: 'wiz_paradox', title: 'Парадокс' },
        { id: 'wiz_wyvern', title: 'Виверна' },
        { id: 'wiz_phoenix', title: 'Феникс' }
    ],
    wiz_archon: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/vyrs-astonishing-aura-Unique_Chest_Set_13_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 2руч, 70🌒 1 + сфера</p><p>🛡️ — <b>Архонт</b> (Выр)</p><p>1, 2 Профа — Поле боя, Белиал</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Смелость | 2️⃣ Несгибаемая воля<br>3️⃣ Ускоренное восстановление | 4️⃣ ❗Аномалия❗, Жив. Защита<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любой навык | 2️⃣ Любой навык | 3️⃣ Кольцо льда<br>4️⃣ ❗Телепорт❗, Силовая волна | 5️⃣ Магическое оружие | 6️⃣ Архонт` },
    wiz_elements: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/tal-rashas-relentless-pursuit-Unique_Chest_014_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1 + сфера</p><p>🛡️ — <b>Тал Раши</b></p><p>1, 2 Профа — Серебряный шпиль 2, Диабло</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Сила стихий | 2️⃣ Паралич<br>3️⃣ Живительная защита | 4️⃣ ❗Аномалия❗, Жажда энергии<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Шоковый разряд | 2️⃣ Любой навык | 3️⃣ Любой навык<br>4️⃣ Снежная буря | 5️⃣ ❗Телепорт❗, Фамилиар | 6️⃣ Черная дыра` },
    wiz_paradox: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/harness-of-truth-Unique_Chest_Set_02_p2'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1 + сфера, 70🌒 2руч</p><p>🛡️ — <b>Дельсир</b></p><p>1, 2 Профа — Каменный форт, Осадный зверь</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Смелость | 2️⃣ Покорение<br>3️⃣ Гениальность | 4️⃣ ❗Аномалия❗, Сила стихий<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Призрачный клинок | 2️⃣ Магическая сфера<br>3️⃣ ❗Телепорт❗, Энергетический взрыв | 4️⃣ Замедление времени<br>5️⃣ Энергетический вихрь | 6️⃣ Ледяной доспех` },
    wiz_wyvern: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/typhons-thorax-P68_Unique_Chest_Set_03'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1 + сфера</p><p>🛡️ — <b>Тифон</b></p><p>1, 2 Профа — Кладбище Бриатборн, Магда</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Живительная защита | 2️⃣ Жажда энергии<br>3️⃣ Хрупкий разрушитель | 4️⃣ ❗Аномалия❗, Покорение<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любой навык | 2️⃣ Любой навык<br>3️⃣ ❗Телепорт❗, Любой навык | 4️⃣ Гидра<br>5️⃣ Доспех бури | 6️⃣ Зеркальные отражения` },
    wiz_phoenix: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/firebirds-breast-Unique_Chest_Set_06_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1 + щит, 70🌒 1 + сфера</p><p>🛡️ — <b>Огненная птица</b></p><p>1, 2 Профа — Серебряный шпиль 1, Адрия</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Живительная защита | 2️⃣ Жажда энергии<br>3️⃣ Расплывчатый силуэт | 4️⃣ ❗Аномалия❗, Хрупк. Разрушитель<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Электрошок | 2️⃣ Маг поток | 3️⃣ ❗Телепорт❗, Любой<br>4️⃣ Метеорит | 5️⃣ Энергетический доспех | 6️⃣ Черная дыра` },

    // МОНАХ
    monk_menu: [
        { id: 'monk_avenger', title: 'Мститель' },
        { id: 'monk_tyrant', title: 'Тиран' },
        { id: 'monk_terror', title: 'Террор' },
        { id: 'monk_harmony', title: 'Гармония' },
        { id: 'monk_destroyer', title: 'Дестроер' }
    ],
    monk_avenger: { content: `<a href="#" onclick="window.openIframe('https://us.diablo3.blizzard.com/ru-ru/item/sunwukos-soul-Unique_Chest_Set_11_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+щит, 70🌒 1+1</p><p>🛡️ — <b>Сунвуко</b></p><p>1 Профа — Сады надежды | 2 Профа — Кхом</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Шестое чувство | 2️⃣ Перехват инициативы<br>3️⃣ Твердая воля | 4️⃣ Познание смерти / Путь стража<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Касание смерти | 2️⃣ Хвост дракона ИЛИ Волна света<br>3️⃣ Покой | 4️⃣ Хлещущий ветер<br>5️⃣ Мощный рывок / Ураганный удар | 6️⃣ Мантра любая` },
    monk_tyrant: { content: `<a href="#" onclick="window.openIframe('https://us.diablo3.blizzard.com/ru-ru/item/heart-of-the-crashing-wave-Unique_Chest_Set_08_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+1</p><p>🛡️ — <b>Тысяча бурь</b></p><p>1 Профа — Бескрайние пески | 2 Профа — Белиал</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Перехват инициативы | 2️⃣ Путь стража<br>3️⃣ Стремительность | 4️⃣ Познание смерти / Решимость<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Сотни кулаков | 2️⃣ Любое | 3️⃣ Дыхание небес<br>4️⃣ Мощный рывок / Хлещущий ветер | 5️⃣ Прозрение | 6️⃣ Мантра Осуждения` },
    monk_terror: { content: `<a href="#" onclick="window.openIframe('https://us.diablo3.blizzard.com/ru-ru/item/ulianas-heart-Unique_Chest_Set_01_p3'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 любое</p><p>🛡️ — <b>Ульяна</b></p><p>1 Профа — Кладбище | 2 Профа — Штурмовой зверь</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Перехват инициативы | 2️⃣ Светоч итара<br>3️⃣ Неземной ритм ИЛИ Стремительность | 4️⃣ Познание смерти / Путь стража<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Кулаки грома | 2️⃣ Мощный рывок / Любое<br>3️⃣ Ослепляющая вспышка | 4️⃣ Взрывное касание<br>5️⃣ Семь сторон света | 6️⃣ Мантра исцеления` },
    monk_harmony: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/innas-vast-expanse-Unique_Chest_015_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 2руч, 70🌒 любое</p><p>🛡️ — <b>Инна</b></p><p>1 Профа — Собор 1 | 2 Профа — Диабло</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Решимость | 2️⃣ Гармония<br>3️⃣ Безжалостный натиск | 4️⃣ Познание смерти / Единство<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любой навык | 2️⃣ Любой навык | 3️⃣ Святая святых<br>4️⃣ Мощный рывок / Любой навык | 5️⃣ Таинственный союзник | 6️⃣ Мантра любая` },
    monk_destroyer: { content: `<a href="#" onclick="window.openIframe('https://us.diablo3.blizzard.com/ru-ru/item/lamellars-of-justice-P67_Unique_Chest_Set_02'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 2руч, 70🌒 1+1</p><p>🛡️ — <b>Эталон справедливости</b></p><p>1 Профа — Путь утопших | 2 Профа — Магда</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Перехват инициативы | 2️⃣ Решимость<br>3️⃣ Твердая воля | 4️⃣ Познание смерти / Шестое чувство<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Волна увечий | 2️⃣ Стремительность урагана | 3️⃣ Любой навык<br>4️⃣ Хлещущий ветер | 5️⃣ Мощный рывок / Любой навык | 6️⃣ Мантра спасения` },

    // КОЛДУН
    wd_menu: [
        { id: 'wd_voodoo', title: 'Вуду' },
        { id: 'wd_reaper', title: 'Жнец' },
        { id: 'wd_cemetery', title: 'Кладбище' },
        { id: 'wd_necrosis', title: 'Некроз' },
        { id: 'wd_ghost', title: 'Призрак' }
    ],
    wd_voodoo: { content: `<a href="#" onclick="window.openIframe('https://us.diablo3.blizzard.com/ru-ru/item/helltooth-tunic-Unique_Chest_Set_16_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+оберег, 70🌒 1+щит</p><p>🛡️ — <b>Адский зуб</b></p><p>1 Профа — Собор 2 | 2 Профа — Магда</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Полуночный пир | 2️⃣ Шаг за грань<br>3️⃣ Рьяная преданность | 4️⃣ Вместилище духов / Первобытная стойкость<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Трупные пауки | 2️⃣ Поступь духа / Объятия смерти<br>3️⃣ Псы | 4️⃣ — | 5️⃣ Пираньи + Стена смерти | 6️⃣ Громадень` },
    wd_reaper: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/jade-harvesters-peace-Unique_Chest_Set_09_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+щит, 70🌒 1+пред</p><p>🛡️ — <b>Нефритовый жрец</b></p><p>1 Профа — Поле боя | 2 Профа — Адрия</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Медленная смерть | 2️⃣ Болотная гармония<br>3️⃣ Ритуал доверия | 4️⃣ Вместилище духов / Несправедливая смерть<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Нашествие жаб | 2️⃣ Мстительный дух + Рой саранчи<br>3️⃣ Ужас | 4️⃣ Жатва душ | 5️⃣ Поступь духа / Стена смерти | 6️⃣ —` },
    wd_cemetery: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/zunimassas-marrow-Unique_Chest_016_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+оберег, 70🌒 1+щит</p><p>🛡️ — <b>Зунимасса</b></p><p>1 Профа — Собор 2 | 2 Профа — Магда</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Полуночный пир | 2️⃣ Шаг за грань<br>3️⃣ Рьяная преданность | 4️⃣ Вместилище духов / Первобытная стойкость<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Дротик | 2️⃣ Любое | 3️⃣ Псы | 4️⃣ —<br>5️⃣ Поступь духа / Пираньи | 6️⃣ Армия фетишей + Громадень` },
    wd_necrosis: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/arachyrs-carapace-Unique_Chest_Set_02_p3'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 2руч, 70🌒 1+оберег</p><p>🛡️ — <b>Арахир</b></p><p>1 Профа — Облачные стены | 2 Профа — Диабло</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Поиски прозрения | 2️⃣ Ритуал доверия<br>3️⃣ Шаг за грань | 4️⃣ Вместилище духов / Болотная гармония<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Трупные пауки ИЛИ Жабы | 2️⃣ Огненные нетопыри<br>3️⃣ Сглаз | 4️⃣ Поступь духа / Всеобщее помешательство<br>5️⃣ Пираньи | 6️⃣ Вуду` },
    wd_ghost: { content: `<a href="#" onclick="window.openIframe('https://us.diablo3.blizzard.com/ru-ru/item/mundunugus-robe-P68_Unique_Chest_Set_04'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+оберег</p><p>🛡️ — <b>Мундунугу</b></p><p>1 Профа — Сады надежды 1 | 2 Профа — Штурмовой зверь</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Беспокойные духи | 2️⃣ Вместилище духов / Ритуал доверия<br>3️⃣ Несправедливая смерть | 4️⃣ Болотная гармония<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Огненная бомба | 2️⃣ Мстительный дух<br>3️⃣ Поступь духа | 4️⃣ Жатва душ<br>5️⃣ Призрачный шквал | 6️⃣ Вуду` },

    // КРЕСТОНОСЕЦ
    crusader_menu: [
        { id: 'crus_formation', title: 'Строй' },
        { id: 'crus_insight', title: 'Озарение' },
        { id: 'crus_bravery', title: 'Храбрость' },
        { id: 'crus_reaction', title: 'Отдача' },
        { id: 'crus_wrath', title: 'Гнев' }
    ],
    crus_formation: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/rolands-bearing-Unique_Chest_Set_01_p1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 2руч + щит</p><p>🛡️ — <b>Роланд</b></p><p>1 Профа — Руины корвуса | 2 Профа — Магда</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Божественная мощь | 2️⃣ Праведность<br>3️⃣ Обновление | 4️⃣ ❗Непроб. Броня❗, Многоцветие<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любое | 2️⃣ Удар щитом ИЛИ Широкий замах<br>3️⃣ Любое | 4️⃣ ❗Скакун❗, Любое | 5️⃣ Любое | 6️⃣ Любое` },
    crus_insight: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/heart-of-the-light-Unique_Chest_Set_03_p3'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+щит</p><p>🛡️ — <b>Поиски света</b></p><p>1 Профа — Сады надежды 2 | 2 Профа — Адрия</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Рвение | 2️⃣ Резкость | 3️⃣ Праведный гнев<br>4️⃣ ❗Непроб. Броня❗, Ни шагу назад<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любое | 2️⃣ Освящённый молот | 3️⃣ Любое<br>4️⃣ Насмешка | 5️⃣ ❗Скакун❗, Любое | 6️⃣ Падающий меч` },
    crus_bravery: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/brigandine-of-valor-P67_Unique_Chest_Set_01'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+щит</p><p>🛡️ — <b>Эгида доблести</b></p><p>1 Профа — Собор 3 | 2 Профа — Раканот</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Рвение | 2️⃣ Несокрушимый боец | 3️⃣ Священная твердыня<br>4️⃣ ❗Непроб. Броня❗, Многоцветие<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любое | 2️⃣ Длань небес | 3️⃣ Любое<br>4️⃣ ❗Скакун❗, Любое | 5️⃣ Принцип справедливости | 6️⃣ Ярость небес` },
    crus_reaction: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/burden-of-the-invoker-Unique_Shoulder_Set_12_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 20🌒 1+щит</p><p>🛡️ — <b>Шипы призывателя</b></p><p>1 Профа — Руины корвуса | 2 Профа — Магда</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Железная дева | 2️⃣ Фанатизм | 3️⃣ Ни шагу назад<br>4️⃣ ❗Непроб. Броня❗, Обновление<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Наказание ИЛИ Удар сплеча | 2️⃣ Любое | 3️⃣ Любое<br>4️⃣ Насмешка | 5️⃣ Любое | 6️⃣ ❗Скакун❗, Любое` },
    crus_wrath: { content: `<a href="#" onclick="window.openIframe('https://eu.diablo3.blizzard.com/ru-ru/item/breastplate-of-akkhan-Unique_Chest_Set_10_x1'); return false;" style="display: block; text-align: center; padding: 10px; border: 2px solid #d4af37; color: #d4af37; text-decoration: none; font-family: 'Cinzel Decorative'; margin-bottom: 15px; background: rgba(212,175,55,0.1);">💠 ОТКРЫТЬ СЭТ</a><p>⚔️ — 2руч + щит</p><p>🛡️ — <b>Аккан</b></p><p>1 Профа — Поле боя | 2 Профа — Белиал</p><hr><p style="color: #66ccff;"><b>👣 ПАССИВКИ:</b></p>1️⃣ Божественная мощь | 2️⃣ Ни шагу назад<br>3️⃣ Многоцветие | 4️⃣ ❗Непроб. Броня❗, Несокр. боец<hr><p style="color: #66ff66;"><b>🐾 АКТИВКИ:</b></p>1️⃣ Любое | 2️⃣ Любое | 3️⃣ Любое<br>4️⃣ ❗Скакун❗, Любое | 5️⃣ Принцип доблести | 6️⃣ Поборник Акарата` },
    g_cl1: { 
        title: '1 класс — 150%',
        content: `
        <div class="craft-row" style="justify-content: center; gap: 20px;">
                <button class="craft-btn buy" onclick="openBuySellAGradeModal('buy', 1.5)">КУПИТЬ</button>
                <button class="craft-btn sell" onclick="openBuySellAGradeModal('sell', 1.5)">ПРОДАТЬ</button>
            </div>
            <div id="selected-agrade-item-display" style="text-align: center; color: #ffd700; margin-bottom: 10px; font-weight: bold; min-height: 1.2em;"></div>
            <input type="text" oninput="window.filterItems(this)" placeholder="Поиск предмета..." style="width: 100%; padding: 8px; background: #000; border: 1px solid #555; color: #fff; margin-bottom: 15px; box-sizing: border-box;">
            <input type="text" name="search-items-150" oninput="window.filterItems(this)" placeholder="Поиск предмета..." style="width: 100%; padding: 8px; background: #000; border: 1px solid #555; color: #fff; margin-bottom: 15px; box-sizing: border-box;">
            <div class="item-list-container" style="max-height: 400px; overflow-y: auto; padding-right: 5px;">
                <div style="display: flex; flex-wrap: wrap; gap: 20px;">
                    <div style="flex: 1; min-width: 250px;">
                        <p style="color: #d4af37; font-size: 1.2rem; border-bottom: 1px solid #5a0000; margin-bottom: 10px;">🗡️ ОРУЖИЕ</p>
                        <div class="item-category"><b style="color: #ff9900;">Оберег:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Взгляд смерти</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Гомункул</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ухкапианский змей</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Хватка Вилкена</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Злоба</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Сфера:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Гравированный знак</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Триумвират</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Сфера бездонной пропасти</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Колчан:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Ищущие грех</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Стрелы Света</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Рюкзак бомбардира</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Девятый ранец Цирри</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Походный колчан Эмимеи</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Панацея Августины</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наследие мертвеца</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Топор:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Завет Мордуллу</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Булава:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Шеферский молот</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Отголосок ярости</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кинжал:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Веер лорда Гринстоуна</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Жало Карли</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Копье:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Трехсотое копье</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Меч:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Лазурная ярость</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Меч злой воли</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Желание Смерти</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Осколок ненависти</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Меч вихрей</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Верная память</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Плеть</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Уничтожитель Сталгарда</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Клинок пророчества</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Церем. Нож:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Кинжал-дротик</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Священный пожинатель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Брадобрей</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кукри из звездного металла</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Шинкователь Ву</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кистевое:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Хрустальный кулак</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Терзатель плоти</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Шраморез</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кулак Аз'Турраска</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Вон Ким Лау</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Клинок Киоширо</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ветер мщения</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Львиные когти</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кистень:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Свет во тьме</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Когти кречета</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Довод Джоанны</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Дополнение Аккана</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Удел свирепых</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Золоченый свежеватель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Снисходительность Аккана</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Мощное:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Прорубатель фьордов</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Гордость Амбо</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Клинок полководца</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Клятвохранитель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Оскверненное наследие</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Почет Бастиона</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ярость исчезнувшей вершины</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Молот правосудия</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Клинок легендарного племени</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Посох:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Посох рукокрылых</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Великий визирь</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Нестабильный скипетр</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Змеиный жезл</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Жезл Во</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Элемент судьбы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Эфирный странник</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Дайбо:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Равновесие</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Поток вечности</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ароматический храмовый факел</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Лук:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Изогнутый лук Яна</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Львиный лук Хашира</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Погибель Одиссея</span></div>
                        <div class="item-category"><b style="color: #ff9900;">2арб:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Мантикора</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Натиск воджанни</span></div>
                        <div class="item-category"><b style="color: #ff9900;">1арб:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Утренняя заря</span></div>
                    </div>
                    <div style="flex: 1; min-width: 250px;">
                        <p style="color: #d4af37; font-size: 1.2rem; border-bottom: 1px solid #5a0000; margin-bottom: 10px;">🛡️ БРОНЯ</p>
                        <div class="item-category"><b style="color: #ff9900;">Тело:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Железное сердце</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кираса акилы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Плащ Бекинсейл</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Плащ гарвульфа</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Голова:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Сломанная корона</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Боевой шлем Кассара</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Гьяна на касу</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Законы Сефа</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Глаз Пешкова</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Камень безумия</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Злобная карнавальная маска</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Маска Йерама</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кровожадный оскал</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Корона Примаса</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Свами</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Судья</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Наплечники:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Наплечники стража смерти</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Монолог Лефевр</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Оплечье поддержания</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ярость Древних</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Мерзкий страж</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Запястья:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Кровавые наручи Ашнагарра</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Доспехи Гунгдо</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Реликвия Кесаря</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Гордость Пинто</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Скрепы малых богов</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кандалы Аккана</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Обвязки Мортика</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Латные щитки Сечерона</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наруч ярости</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Витки первого паука</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Обмотки ясности</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наручи Йерама</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наручи первожителей</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Безрассудство Ранслора</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наручи разрушения</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Перчатки:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Таскер и Тео</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Пояс:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Шафрановый кушак</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ведьмин пояс</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Вериги ушедшей</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Позор Дельсира</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Душа Киоширо</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Пояс из лианы Бакули</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Невероятная цепь Фазулы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Путы Хергбраша</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Ноги:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Зачумленные штаны</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Штаны Хаммера</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Проклятые штаны господина Яна</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Болотные штаны</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Покорители подземных глубин</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Ступни:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Очень простые сапоги</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Танцевальные туфли Риверы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Чулки Лута</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Сапоги пренебрежения</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Гордость Нильфур</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Амулет:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Ожерелье Попрыгушки</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Благодать предков</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кольцо:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Кольцо силы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кольцо королевской роскоши</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Исцеление Манальда</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ореол Карини</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Палец низкорослого человека</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кольцо Найджела</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Обсидиановое кольцо зодиака</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Свет справедливости</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Щит:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Отпор</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Эберли-каро</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Башня из слоновой кости</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Щит ярости</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Йеканборг</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Пробуждение Акарата</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Пиро Марелла</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Щит Джоанны</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Гнев Фридейра</span></div>
                    </div>
                </div>
            </div>
        `
    },
    g_cl2: { 
        title: '2 класс — 100%',
        content: `
        <div class="craft-row" style="justify-content: center; gap: 20px;">
                <button class="craft-btn buy" onclick="openBuySellAGradeModal('buy', 1.0)">КУПИТЬ</button>
                <button class="craft-btn sell" onclick="openBuySellAGradeModal('sell', 1.0)">ПРОДАТЬ</button>
            </div>
            <div id="selected-agrade-item-display" style="text-align: center; color: #ffd700; margin-bottom: 10px; font-weight: bold; min-height: 1.2em;"></div>
            <input type="text" oninput="window.filterItems(this)" placeholder="Поиск предмета..." style="width: 100%; padding: 8px; background: #000; border: 1px solid #555; color: #fff; margin-bottom: 15px; box-sizing: border-box;">
            <input type="text" name="search-items-100" oninput="window.filterItems(this)" placeholder="Поиск предмета..." style="width: 100%; padding: 8px; background: #000; border: 1px solid #555; color: #fff; margin-bottom: 15px; box-sizing: border-box;">
            <div class="item-list-container" style="max-height: 400px; overflow-y: auto; padding-right: 5px;">
                <div style="display: flex; flex-wrap: wrap; gap: 20px;">
                    <div style="flex: 1; min-width: 250px;">
                        <p style="color: #d4af37; font-size: 1.2rem; border-bottom: 1px solid #5a0000; margin-bottom: 10px;">🗡️ ОРУЖИЕ</p>
                        <div class="item-category"><b style="color: #ff9900;">Оберег:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Триумф Шукрани</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Нечто из глубин</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Искания Генриха</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Отвратительный улей</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Сфера:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Зимний ветер</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Отражающий свет шар</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Свет добродетели</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Сгусток ненависти Микена</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Око</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Неземной берег</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Первородная душа</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Колчан:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Шипы лютой ненависти</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Топор:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Секач</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Раскалыватель небес</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Палач</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Вспышка ярости</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Похититель Мессершмитта</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Пылающая головня</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Пылающий колун</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Завистливый клинок</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Булава:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Искра жизни Артефа</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Горнило</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Небесный страж</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Сын Одина</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Скипетр безумного монарха</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Молот бдительности Джейса</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кинжал:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Чародейский шип</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Юн-Чан-До</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Копье:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Арреатский закон</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Резное копье</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Осада</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Бдительность</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Меч:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Громовая Ярость</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ледяное сердце</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Громовержец</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ин-Гиом</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Максимус</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Возражение Кэма</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кровный брат</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Оскверненный Испепелитель</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Церем. Нож:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Смертельное перерождение</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Свежеватель Рен'хо</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Последний вздох</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Хватка паучьей королевы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Лезвие Анессази</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Гидбинн</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кистевое:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Зубодробитель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Удар безумия</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Золоченая плеть</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кистень:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Милость Юстиниана</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Стремительный кистень</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Воздаяние Кассара</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Непоколебимая вера</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кистень Вознесшегося</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Губительный осколок</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ужас смертности</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Мощное:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Немилосердная булава</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Скорбь Мадавка</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Посох:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Прорицатель Су Вон</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Аварион</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Полынь</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Звездный огонь</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Жест Орфея</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Дайбо:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Боевой посох генерала Цюана</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Летящий дракон</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Лук:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Крайдершот</span></div>
                        <div class="item-category"><b style="color: #ff9900;">2арб:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Буриза-до кэнону</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Стреломет Ченона</span></div>
                        <div class="item-category"><b style="color: #ff9900;">1арб:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Пленитель Преисподней</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наследство Валлы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">К'мар Тенклип</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Катастрофа</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Крылья Лианны</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Крепостная баллиста</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Погибель демона</span></div>
                    </div>
                    <div style="flex: 1; min-width: 250px;">
                        <p style="color: #d4af37; font-size: 1.2rem; border-bottom: 1px solid #5a0000; margin-bottom: 10px;">🛡️ БРОНЯ</p>
                         <div class="item-category"><b style="color: #ff9900;">Тело:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Пепельный мундир</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Доспех доброго регента</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Чёрное перо</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Накидка темной ночи</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Голова:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Лицо Гюнса</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Корона леорика</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Низложение гордыни</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Клобук предсказателя смерти</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Резонирующий череп</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Лик Андариэль</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Глаз разума</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Несломимый дух Кекеги</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Взгляд Тзо Крина</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кетцалькоатль</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Лицо Гьюа</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Тикланский лик</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Колпак темного мага</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Викалике архимага</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Бархатный камарал</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Наплечники:</b> —</div>
                        <div class="item-category"><b style="color: #ff9900;">Запястья:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Кровавые латные щитки</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наручи возмездия</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Древние защитники Парты</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наручи силача</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Перчатки:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Перчатки поклонения</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Каменные рукавицы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Вызов святого Арчью</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Магические кулаки</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Обжигающий холод</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Пояс:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Златотканная перевязь</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ненасытный пояс</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Священная перевязь</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Пояс из ушей</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ночной кошмар Себора</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Всепоражающий удар</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Пояс-ножны</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Навязчивый ремень</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Обмотки Хводжа</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Цепь Омрина</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Вервие Шермы</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Цепь Теней</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Ноги:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Сделка со смертью</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Ступни:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Призрачные башмаки</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Огнеупорные сапоги</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Сапоги для хождения по льду</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Амулет:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Покровительство лунного света</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Всепоглощающее желание</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Талисман Араноха</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Камея графини Юлии</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Суть Йохана</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Дух времени</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Золото Кимбо</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Калейдоскоп Мары</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Звезда Азкаранта</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Амулет Ксефирии</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Восшествие Гальциона</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кольцо:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Петля Пандемония</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Нарушенные обещания</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Палец высокого человека</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Воровское кольцо Решель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кольцо залов сожаления</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Огромная печатка Рогара</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Знак судьбы</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Щит:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Атрибут культа</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Шипы Во'Тойяза</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Замораживающий отклонитель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Защитник Вестмарша</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Спасение</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Последний свидетель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Священный оплот</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Возвышенные убеждения</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Адский череп</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Неумолимая фаланга</span></div>
                    </div>
                </div>
            </div>
        ` 
    },
    g_cl3: { 
        title: '3 класс — 50%',
        content: `
        <div class="craft-row" style="justify-content: center; gap: 20px;">
                <button class="craft-btn buy" onclick="openBuySellAGradeModal('buy', 0.5)">КУПИТЬ</button>
                <button class="craft-btn sell" onclick="openBuySellAGradeModal('sell', 0.5)">ПРОДАТЬ</button>
            </div>
            <div id="selected-agrade-item-display" style="text-align: center; color: #ffd700; margin-bottom: 10px; font-weight: bold; min-height: 1.2em;"></div>
            <input type="text" oninput="window.filterItems(this)" placeholder="Поиск предмета..." style="width: 100%; padding: 8px; background: #000; border: 1px solid #555; color: #fff; margin-bottom: 15px; box-sizing: border-box;">
            <input type="text" name="search-items-50" oninput="window.filterItems(this)" placeholder="Поиск предмета..." style="width: 100%; padding: 8px; background: #000; border: 1px solid #555; color: #fff; margin-bottom: 15px; box-sizing: border-box;">
            <div class="item-list-container" style="max-height: 400px; overflow-y: auto; padding-right: 5px;">
                <div style="display: flex; flex-wrap: wrap; gap: 20px;">
                    <div style="flex: 1; min-width: 250px;">
                        <p style="color: #d4af37; font-size: 1.2rem; border-bottom: 1px solid #5a0000; margin-bottom: 10px;">🗡️ ОРУЖИЕ</p>
                        <div class="item-category"><b style="color: #ff9900;">Топор:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Гендзанику</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Крюк Мясника</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Пылающий топор Санкиса</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Разделочный нож Мясника</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Булава:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Крушитель душ</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Катаклизм</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Разлом</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Соланиум</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Сотрясатель земли</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кинжал:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Свинорез</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Клинок кровавой магии</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Острие кровавой магии</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Копье:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Коровий бердыш</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Меч:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Разрубатель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Рассекатель небес</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Посох:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Жезл арреатских недр</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наказание Валтека</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Средоточие Малота</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Мучитель</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Безумие Слорака</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Лук:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Крыло ворона</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Дурной глаз</span></div>
                        <div class="item-category"><b style="color: #ff9900;">2арб:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Орудие демона</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Гноестрел</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Адский пригвоздитель</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Цер. Нож / Кистевое / Кистень / Мощное / Дайбо / 1арб:</b> —</div>
                    </div>
                    <div style="flex: 1; min-width: 250px;">
                        <p style="color: #d4af37; font-size: 1.2rem; border-bottom: 1px solid #5a0000; margin-bottom: 10px;">🛡️ БРОНЯ</p>
                        <div class="item-category"><b style="color: #ff9900;">Тело:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Кольчуга</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Хаори ши мидзу</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Золотая кожа</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Обманный плащ</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Голова:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Грозовой ворон</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Наплечники:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Наплечные щитки возвращения</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наплечье Короля-скелета</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Наплеч Закары</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Запястья:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Варжечанские боевые наручи</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кастерианские накулачники</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Обещание славы</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Перчатки:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Рукавицы гладиатора</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Пояс:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Сила Громовержца</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Ремень для правки бритв</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Ноги:</b> — </div>
                        <div class="item-category"><b style="color: #ff9900;">Ступни:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Грязеступы Железной Ноги</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Амулет:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Золотое ожерелье Леорика</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Энергетическая ловушка Дову</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Осколок жизни Ракова</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Одержимость Вахо</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Кольцо:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Кольцо алчности</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Кольцо-головоломка</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Аркстон</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Обручальное кольцо Бул-Катоса</span></div>
                        <div class="item-category"><b style="color: #ff9900;">Щит:</b> <span class="selectable-item" onclick="selectAGradeItem(this)">Костяная стена</span>, <span class="selectable-item" onclick="selectAGradeItem(this)">Воинский вал</span></div>
                    </div>
                </div>
            </div>
        ` 
    }
};
